a = input('Digite um valor: ')
print('O tipo primitivo desse valor eh: ', type(a))
print('So tem espacos? ', a.isspace())
print('Eh numero? ', a.isnumeric())
print('Eh alfabetico?', a.isalpha())
print('Eh alfanumerico?', a.isalnum())
print('Esta em maiuscula?', a.isupper())
print('Esta em minuscula?', a.lower())
print('Esta capitalizado?', a.istitle())