name = input('What is your name? ')
weather = input('How is the weather outside? ')
wear = input('What should I wear to go outside? ')
# print('My name is',name,'. The weather outside is',weather,'. You should wear', wear,'.')
print('My name is {}, today is {} outside, I will wear {}'.format (name, weather, wear,'.'))
